CREATE SCHEMA IF NOT EXISTS bankdemo;
DROP TABLE IF EXISTS bankdemo.operations;
CREATE TABLE IF NOT EXISTS bankdemo.operations(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP NOT NULL,
	amount DOUBLE PRECISION NOT NULL,
	action VARCHAR(10) NOT NULL,
	currency VARCHAR(3) NOT NULL CHECK (CHAR_LENGTH(currency) = 3),
	sender INTEGER,
	recipient INTEGER,
	bank VARCHAR(30) NOT NULL
);