infinispan.client.hotrod.server_list=127.0.0.1:11222
# infinispan.client.hotrod.host=${infinispan.client.hotrod.server_list.split(':')[0]}
# infinispan.client.hotrod.port=${infinispan.client.hotrod.server_list.split(':')[1]}