CREATE SCHEMA IF NOT EXISTS bankdemo;
DROP TABLE IF EXISTS bankdemo.accounts;
CREATE TABLE IF NOT EXISTS bankdemo.accounts(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP,
	is_active BOOLEAN NOT NULL,
	name VARCHAR(20) NOT NULL,
	surname VARCHAR(40) NOT NULL,
	phone VARCHAR(10) UNIQUE NOT NULL CHECK (CHAR_LENGTH(phone) = 10),
	email VARCHAR(60) UNIQUE NOT NULL,
	birthday DATE NOT NULL,
	password VARCHAR(60) NOT NULL,
	bills INTEGER ARRAY,
	roles VARCHAR ARRAY
);